import { UI } from '@/libs/ui/src';
import { Button } from '@/libs/ui/src/atoms/button';
import './global.scss';

export const metadata = {
  title: 'Welcome to portfolio',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <UI></UI>
      <Button variant="outline">Butt on</Button>
      <body>{children}</body>
    </html>
  );
}
