name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  checks: write
  pull-requests: write
  issues: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'

      - run: pnpm install
      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t build
    # - run: npx nx affected --parallel 1 -t e2e-ci
